version: '3'

services:
  cadvisor:
    image: gcr.io/google-containers/cadvisor:v0.36.0
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.0.1
    pid: "host"
    volumes:
      - /:/host:ro

  prometheus:
    image: quay.io/prometheus/prometheus:v2.20.1
    user: '1000'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      - bootstrap.memory_lock=true
      - transport.host=127.0.0.1
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - network.host=
      - http.host=0.0.0.0
      - indices.id_field_data.enabled=true
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=changeme
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.0
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
      - 5601:5601
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml

  agent:
    image: docker.elastic.co/beats/elastic-agent:7.9.0
    volumes:
      - ./elastic-agent.yml:/usr/share/elastic-agent/elastic-agent.yml
    command: ["-e", "-v"]
