version: '3'

services:
  cadvisor:
    image: google/cadvisor:v0.33.0
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

  node_exporter:
    image: quay.io/prometheus/node-exporter:v0.17.0
    pid: "host"
    volumes:
      - /:/host:ro,rslave

  prometheus:
    image: quay.io/prometheus/prometheus:v2.8.1
    user: '1000'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0-rc2
    user: '1000'
    environment:
      - bootstrap.memory_lock=true
      - transport.host=127.0.0.1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0-rc2
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
      - 5601:5601
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL

  metricbeat_no_source:
    image: docker.elastic.co/beats/metricbeat:7.0.0-rc2
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
    environment:
      INDEX_NAME: metricbeat_no_source
    command: [
      "-e", "-v", "--strict.perms=false",
      # Disable _source field:
      "-E", "setup.template.settings._source.enabled=false",
    ]

  metricbeat_with_source:
    image: docker.elastic.co/beats/metricbeat:7.0.0-rc2
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
    environment:
      INDEX_NAME: metricbeat_with_source
    command: ["-e", "-v", "--strict.perms=false"]